export const productColumns = [
    { field: 'id', headerName: 'Mã HĐ', width: 120 }, {
        field: "bills", headerName: "Họ Tên Khách Hàng", width: 250, renderCell: (params) => {
            return (
                <div className="cellWithImg">
                    {params.row.hokh + " "}{params.row.tenkh}
                </div>
            );
        },
    },
    {
        field: "ngaylap", headerName: "Ngày Lập Hóa Đơn", width: 220,
    },
    {
        field: "tongtien", headerName: "Tổng Tiền", width: 220,
    },
    {
        field: "trangthai", headerName: "Tình Trạng", width: 180,
    },


];


export const productRows = [
    {
        id: 1,
        manv: "1",
        makh: "21",
        hokh: "Cẩm",
        tenkh: "Duyên",
        ngaysinh: "0328332105",
        diachi: "camduyen20011@gmail.com",
        sdt: "abcsadf",
        email: "Nữ",
        ngaylap: "20/07/2001",
        tongtien: "30000029",
        trangthai: "Hoàn thành",
    },
    {
        id: 2,
        manv: "1",
        makh: "21",
        hokh: "Cẩm",
        tenkh: "Duyên",
        ngaysinh: "0328332105",
        diachi: "camduyen20011@gmail.com",
        sdt: "abcsadf",
        email: "Nữ",
        ngaylap: "20/07/2001",
        tongtien: "30000000",
        trangthai: "Hoàn thành",
    },
    {
        id: 3,
        manv: "1",
        makh: "21",
        hokh: "Cẩm",
        tenkh: "Duyên",
        ngaysinh: "0328332105",
        diachi: "camduyen20011@gmail.com",
        sdt: "abcsadf",
        email: "Nữ",
        ngaylap: "20/07/2001",
        tongtien: "23000029",
        trangthai: "Hoàn thành",
    },
    {
        id: 4,
        manv: "1",
        makh: "21",
        hokh: "Cẩm",
        tenkh: "Duyên",
        ngaysinh: "0328332105",
        diachi: "camduyen20011@gmail.com",
        sdt: "abcsadf",
        email: "Nữ",
        ngaylap: "20/07/2001",
        tongtien: "2000000",
        trangthai: "Hoàn thành",
    },
    {
        id: 5,
        manv: "1",
        makh: "21",
        hokh: "Cẩm",
        tenkh: "Duyên",
        ngaysinh: "0328332105",
        diachi: "camduyen20011@gmail.com",
        sdt: "abcsadf",
        email: "Nữ",
        ngaylap: "20/07/2001",
        tongtien: "400000",
        trangthai: "Hoàn thành",
    },
    {
        id: 6,
        manv: "1",
        makh: "21",
        hokh: "Cẩm",
        tenkh: "Duyên",
        ngaysinh: "0328332105",
        diachi: "camduyen20011@gmail.com",
        sdt: "abcsadf",
        email: "Nữ",
        ngaylap: "20/07/2001",
        tongtien: "0328332105",
        trangthai: "Hoàn thành",
    },
    {
        id: 7,
        manv: "1",
        makh: "21",
        hokh: "Cẩm",
        tenkh: "Duyên",
        ngaysinh: "0328332105",
        diachi: "camduyen20011@gmail.com",
        sdt: "abcsadf",
        email: "Nữ",
        ngaylap: "20/07/2001",
        tongtien: "0328332105",
        trangthai: "Hoàn thành",
    },
    {
        id: 8,
        manv: "1",
        makh: "21",
        hokh: "Cẩm",
        tenkh: "Duyên",
        ngaysinh: "0328332105",
        diachi: "camduyen20011@gmail.com",
        sdt: "abcsadf",
        email: "Nữ",
        ngaylap: "20/07/2001",
        tongtien: "0328332105",
        trangthai: "Hoàn thành",
    },
    {
        id: 9,
        manv: "1",
        makh: "21",
        hokh: "Cẩm",
        tenkh: "Duyên",
        ngaysinh: "0328332105",
        diachi: "camduyen20011@gmail.com",
        sdt: "abcsadf",
        email: "Nữ",
        ngaylap: "20/07/2001",
        tongtien: "0328332105",
        trangthai: "Hoàn thành",
    },
    {
        id: 10,
        manv: "1",
        makh: "21",
        hokh: "Cẩm",
        tenkh: "Duyên",
        ngaysinh: "0328332105",
        diachi: "camduyen20011@gmail.com",
        sdt: "abcsadf",
        email: "Nữ",
        ngaylap: "20/07/2001",
        tongtien: "0328332105",
        trangthai: "Hoàn thành",
    },
];